version: "3"

services:
  stan:
    image: nats-streaming:0.24.0-alpine3.15

    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      - 7777:7777

    command:
      [
        "nats-streaming-server",
        "-cid=test-cluster",
        "-m=8222",
        "-mc=10000",
        "-msu=0",
        "-mi=24h",
        "-max_age=24h",
        "-store=FILE",
        "--dir=/nats-filestore",
        "--file_fds_limit=0",
        "-ft_group=ft-test",
        "--cluster_raft_logging=true",
        "--cluster=nats://0.0.0.0:6222",
      ]
# "--routes=nats://nats-streaming-ft:6222"
