apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-base
  labels:
    demo: nfs-pv-base
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.base_pvc }}